// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/goldace-stickers/GoldAce.tsx": () => import("../components/mockups/goldace-stickers/GoldAce.tsx")
};
